#!/bin/bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo 'Parsing slides...'
for f in jade/*.jade; do
  node_modules/jade/bin/jade $f -O generated
done

echo 'Parsing CSS...'
node_modules/less/bin/lessc less/style.less > generated/assets/css/style.css

echo 'Done!'